export const ROUTE = {
    LOGIN:'LOGIN',
    HOME:"HOME",
    SPLASH : 'SPLASH',
    TOURNAMENT_DATA : 'TOURNAMENT_DATA',
    TEAMS_DATA : 'TEAMS_DATA',
    PLAYERS_DATA :'PLAYERS_DATA',
    REVIEW_DATA : 'REVIEW_DATA',
    ADD_FIXTURES:'ADD_FIXTURES',
    VIEW_FIXTURES : 'VIEW_FIXTURES',
    SHOW_FIXTURES : 'SHOW_FIXTURES',
    TOURNAMENT_LANDING_PAGE : 'TOURNAMENT_LANDING_PAGE',
    POINTS_TABLE : 'POINTS_TABLE',
    PLAYERS_RANKING : 'PLAYERS_RANKING',
  };
  